windowrule = no_blur on, match:class fcitx.*
windowrule = no_anim on, match:class fcitx.*
windowrule = stay_focused on, match:class fcitx.*
windowrule = pin on, match:class fcitx.*
windowrule = no_anim on, match:xwayland 0
windowrule = float on, match:title Save File.*
windowrule = float on, match:title Open File.*
windowrule = float on, match:title .*elegram
windowrule = float on, match:title Meet - gee-onpj-ant.*
windowrule = float on, match:title Select a file.*
windowrule = float on, match:class wechat
windowrule = float on, match:class discord
windowrule = float on, match:title Clash for Windows
windowrule = float on, match:class netease-cloud-music
windowrule = float on, match:class motrix
windowrule = float on, match:class Feishu.*
windowrule = float on, match:class 飞书.*
windowrule = float on, match:class Meet.*
windowrule = float on, match:class meet.*
windowrule = float on, match:class 会议.*
windowrule = float on, match:class matplotlib.*
windowrule = float on, match:class cc-switch
windowrule = float on, match:class Matplotlib.*
windowrule = size 1500 1000, float on, match:class Slack
windowrule = opacity 1, match:initial_title WPS.*
windowrule = opacity 1, match:class wechat
