#! /bin/sh

$HOME/.local/bin/scripts/autostart &
$HOME/.config/polybar/launch &
$HOME/.local/bin/scripts/bspwm/edge_event_showbar &
sxhkd &

# bspc monitor -d 1 2 3 4 5 6 7 8 9 10  

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config split_ratio          0.5
bspc config border_width         0
bspc config window_gap           10
bspc config focused_border_color '#bd93f9'
# Color of the border of a focused window of an unfocused monitor.
bspc config active_border_color #ffffff

#bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
# When focusing a monitor, put the pointer at its center.


# use to check class_name:instance_name things
bspc config external_rules_command $HOME/.config/bspwm/external_rules


# (<class_name>|*)[:(<instance_name>|*)[:(<name>|*)]]
bspc rule -a Screenkey  manage=off

bspc rule -a '*:scratchpad:*' sticky=on state=floating layer=above

bspc rule -a qq         sticky=on
bspc rule -a Zathura    state=tiled

bspc rule -a '*:qemu:*' 		state=floating
bspc rule -a biliB      sticky=on state=floating layer = above
bspc rule -a 'wemeetapp' 		state=floating
bspc rule -a 'QQ:qq' 		state=floating
bspc rule -a 'icalingua' 		state=floating


# bspc rule -a VirtualBox\ Manager desktop='^10'

# bspc rule -a Uget-gtk            desktop='^9' #state=floating
# bspc rule -a Transmission-gtk    desktop='^9' #state=floating

# bspc rule -a netease-cloud-music desktop='^8' #state=floating

# bspc rule -a Steam               desktop='^7' #state=floating

