#!/usr/bin/env bash

while [ ! -z "$(pgrep polybar)" ]; do
    killall polybar
done


cat /tmp/polybar1.log > /tmp/polybar2.log
printf "===== Polybar log =====\n\n" > /tmp/polybar1.log &

IsPrimary=0
if type "xrandr" &> /dev/null; then
  # for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  for m in $(polybar -m|sed -e 's/:.*$//g'); do  # with a priority
    if [ $IsPrimary -eq 0 ]; then
        bspc monitor $m -d 1 2 3 4 5 6 7 8 9 10
        MONITOR=$m polybar --reload primary >> /tmp/polybar1.log 2>&1 &
        IsPrimary=1
    else
        bspc monitor $m -d 1 2 3 4 5 6 7 8 9 10
        SUDO_ASKPASS="$HOME/.local/bin/scripts/global/rofipass" MONITOR=$m polybar --reload secondary >> /tmp/polybar1.log 2>&1 &
    fi
  done
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
  polybar --reload primary >> /tmp/polybar1.log 2>&1 &
fi
